package main

import (
	"ds_algo/heap"
	"fmt"
)

func main() {
	h := heap.New()

	h.Insert(7)
	fmt.Println(h.GetArr())
	h.Insert(4)
	fmt.Println(h.GetArr())
	h.Insert(5)
	fmt.Println(h.GetArr())
	h.Insert(6)
	fmt.Println(h.GetArr())
	h.Insert(1)
	fmt.Println(h.GetArr())
	h.Insert(2)
	fmt.Println(h.GetArr())
	h.Insert(30)
	fmt.Println(h.GetArr())
	h.Insert(3)
	fmt.Println(h.GetArr())
	h.Insert(8)
	fmt.Println(h.GetArr())
	h.Insert(9)
	fmt.Println(h.GetArr())
	h.Insert(10)
	fmt.Println(h.GetArr())
	h.Insert(11)
	fmt.Println(h.GetArr())
	h.Insert(12)
	fmt.Println(h.GetArr())
	h.Remove()
	fmt.Println(h.GetArr())
	h.Remove()
	fmt.Println(h.GetArr())
	h.Remove()
	fmt.Println(h.GetArr())
	h.Remove()
	fmt.Println(h.GetArr())
	h.Remove()
	h.Remove()
	h.Remove()
	h.Remove()
	h.Remove()
	h.Remove()
	h.Remove()
	h.Remove()
	h.Remove()
	h.Remove()
	fmt.Println(h.GetArr())

}
